[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "cd /app && python -m uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 120"
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 30
retryInterval = 15
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[envs]
DATABASE_URL = "postgresql://postgres:nGFueZUdBGYipIfpFrxicixchLSgsShM@gondola.proxy.rlwy.net:10790/railway"
DB_HOST = "gondola.proxy.rlwy.net"
DB_PORT = "10790"
DB_NAME = "railway"
DB_USER = "postgres"
DB_PASSWORD = "nGFueZUdBGYipIfpFrxicixchLSgsShM" 