[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/healthcheck"
healthcheckTimeout = 300
healthcheckStartPeriod = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[envs]
DATABASE_URL = "postgresql://postgres:nGFueZUdBGYipIfpFrxicixchLSgsShM@gondola.proxy.rlwy.net:10790/railway"
DB_HOST = "gondola.proxy.rlwy.net"
DB_PORT = "10790"
DB_NAME = "railway"
DB_USER = "postgres"
DB_PASSWORD = "nGFueZUdBGYipIfpFrxicixchLSgsShM" 