[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn railway_app:application -k uvicorn.workers.UvicornWorker -c gunicorn_config.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[envs]
DATABASE_URL = "postgresql://postgres:nGFueZUdBGYipIfpFrxicixchLSgsShM@gondola.proxy.rlwy.net:10790/railway"
DB_HOST = "gondola.proxy.rlwy.net"
DB_PORT = "10790"
DB_NAME = "railway"
DB_USER = "postgres"
DB_PASSWORD = "nGFueZUdBGYipIfpFrxicixchLSgsShM" 