services:
  - type: web
    name: cs2-valuation-api
    env: python
    buildCommand: pip install -r requirements.txt && chmod +x railway_prebuild.sh && ./railway_prebuild.sh
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 4 --timeout 120 --keep-alive 120 railway_app:application -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        value: postgresql://postgres:apuculacata@db.ykaatdxdvkcuryswejkm.supabase.co:5432/postgres?sslmode=prefer&application_name=elite-skins-api&connection_limit=5&keepalives=1&keepalives_idle=30
      # Componentes separados como alternativa
      - key: DB_HOST
        value: db.ykaatdxdvkcuryswejkm.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: apuculacata 